// Secret remains in memory only: reload, reopening or a new tab requires a new console code.
(()=>{const tabToken=Array.from(crypto.getRandomValues(new Uint8Array(32)),x=>x.toString(16).padStart(2,'0')).join('');
const nativeFetch=window.fetch.bind(window);window.fetch=(input,options={})=>{const url=new URL(typeof input==='string'?input:input.url,location.href);if(url.origin===location.origin&&url.pathname.startsWith('/api/stat/')){const headers=new Headers(options.headers||{});headers.set('X-Admin-Tab',tabToken);options={...options,headers}}return nativeFetch(input,options)};
let ticket='';window.adminConsoleLogin=async()=>{const err=document.getElementById('loginErr');const pw=document.getElementById('pw'),btn=document.getElementById('loginBtn');btn.disabled=true;err.textContent='';try{const finish=!!ticket;const r=await fetch('/api/stat/login/'+(finish?'finish':'start'),{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify(finish?{ticket,code:document.getElementById('console-code').value,tab_token:tabToken}:{password:pw.value,admin_name:document.getElementById('admin-name').value,tab_token:tabToken})});const d=await r.json();if(!r.ok)throw new Error(typeof d.detail==='string'?d.detail:'Vérifie les champs.');if(!finish){ticket=d.ticket;document.getElementById('console-step').hidden=false;document.getElementById('console-command').textContent=d.command;pw.value='';btn.textContent='Valider le code serveur';err.textContent=d.message}else{ticket='';document.getElementById('login').classList.add('hidden');document.getElementById('console-code').value='';btn.textContent='Se connecter';document.getElementById('console-step').hidden=true;await load()}}catch(x){err.textContent=x.message}finally{btn.disabled=false}};
window.restartAdminLogin=()=>{ticket='';document.getElementById('console-step').hidden=true;document.getElementById('loginBtn').textContent='Se connecter';document.getElementById('console-code').value='';document.getElementById('loginErr').textContent=''};
setInterval(()=>{if(!document.getElementById('login')?.classList.contains('hidden'))return;fetch('/api/stat/heartbeat',{method:'POST',credentials:'same-origin'}).then(r=>{if(!r.ok){restartAdminLogin();document.getElementById('login').classList.remove('hidden')}}).catch(()=>{})},20000);
addEventListener('pagehide',()=>{fetch('/api/stat/logout',{method:'POST',credentials:'same-origin',keepalive:true}).catch(()=>{})});
addEventListener('pageshow',e=>{if(e.persisted)location.reload()});
})();
