(()=>{
let ticket='',pendingKind='verify',resetToken='';
const guest=document.getElementById('guest'),message=document.getElementById('guestMsg');
if(!guest)return;
function say(t){message.textContent=t;message.setAttribute('role','status')}
async function post(path,data){const r=await fetch('/api/v3/auth/'+path,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});let d;try{d=await r.json()}catch{throw new Error('Réponse serveur indisponible. Réessaie.')}if(!r.ok){const delay=Number(r.headers.get('retry-after'));throw new Error((typeof d.detail==='string'?d.detail:'Vérifie les champs saisis.')+(delay?` Attente : ${Math.ceil(delay/60)} minute(s).`:''))}return d}
async function challenge(form,purpose){let box=form.querySelector('.human-check');if(!box){box=document.createElement('fieldset');box.className='human-check';const legend=document.createElement('legend');legend.textContent='Vérification humaine';box.append(legend);const label=document.createElement('label');label.innerHTML='<span class="human-question">Chargement du calcul…</span><input name="captcha_answer" inputmode="numeric" autocomplete="off" required maxlength="12"><input name="captcha_id" type="hidden">';box.append(label);const refresh=document.createElement('button');refresh.type='button';refresh.className='btn';refresh.textContent='Nouveau calcul';refresh.onclick=()=>challenge(form,purpose);box.append(refresh);form.querySelector('[type="submit"],button:not([type])')?.before(box)}const submit=form.querySelector('[type="submit"],button:not([type])');if(submit)submit.disabled=true;try{const r=await fetch('/api/v3/auth/challenge?purpose='+purpose,{credentials:'same-origin',cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error('Calcul indisponible. Réessaie.');box.querySelector('.human-question').textContent=d.question;box.querySelector('[name=captcha_id]').value=d.captcha_id;box.querySelector('[name=captcha_answer]').value='';if(submit)submit.disabled=false}catch(e){box.querySelector('.human-question').textContent=e.message}}
const pane=document.createElement('section');pane.className='card hidden';pane.id='email-verification';pane.innerHTML='<h2>Validation par email</h2><p id="email-deadline"></p><form id="emailVerifyForm" class="form"><label>Code reçu par email<input name="code" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" maxlength="6" required></label><button class="btn primary" type="submit">Valider mon email</button></form><form id="emailResendForm" class="form"><p>Deux renvois maximum par cycle. Un nouveau code remplace le précédent sans prolonger le délai.</p><button class="btn" type="submit">Renvoyer</button></form>';guest.append(pane);
function pending(d,kind){ticket=d.ticket||ticket;pendingKind=kind;pane.classList.remove('hidden');document.getElementById('emailVerifyForm').hidden=kind==='reset';document.getElementById('email-deadline').textContent=d.expires_at?'Validité jusqu’à '+new Date(d.expires_at).toLocaleTimeString('fr-FR')+'.':'';say(d.message);challenge(document.getElementById('emailResendForm'),'resend')}
for(const [id,path,purpose] of [['loginForm','login','login'],['registerForm','register','register'],['forgotForm','forgot-password','forgot']]){const form=document.getElementById(id);if(id==='loginForm'){const label=document.createElement('label');label.className='remember-session';label.innerHTML='<input type="checkbox" name="remember_me" checked> Rester connecté 30 jours sur cet appareil';form.querySelector('button').before(label)}form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('button:not([type]),button[type=submit]');button.disabled=true;try{const payload=Object.fromEntries(new FormData(form));if(id==='loginForm')payload.remember_me=form.elements.remember_me.checked;const d=await post(path,payload);if(d.verification_required)pending(d,'verify');else if(purpose==='forgot')pending(d,'reset');else{say('Connexion réussie.');location.replace('/app?view=home')}form.querySelector('[name=password]')?.setAttribute('value','');if(form.elements.password)form.elements.password.value=''}catch(x){say(x.message)}finally{await challenge(form,purpose)}}}
document.getElementById('emailVerifyForm').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{await post('verify-email',{ticket,code:e.target.elements.code.value});location.replace('/app?view=home')}catch(x){say(x.message)}finally{b.disabled=false}};
document.getElementById('emailResendForm').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button[type=submit]');b.disabled=true;try{const d=await post('resend-email',{ticket,...Object.fromEntries(new FormData(e.target))});pending(d,pendingKind)}catch(x){say(x.message)}finally{await challenge(e.target,'resend')}};
const fragment=new URLSearchParams(location.hash.slice(1));resetToken=fragment.get('reset')||'';
if(resetToken){history.replaceState(null,'',location.pathname+'?mode=forgot');const form=document.createElement('form');form.id='emailResetForm';form.className='card form';form.innerHTML='<h2>Nouveau mot de passe</h2><label>Mot de passe (12 caractères minimum)<input name="new_password" type="password" autocomplete="new-password" minlength="12" maxlength="128" required></label><button type="submit" class="btn primary">Enregistrer le mot de passe</button>';guest.prepend(form);form.onsubmit=async e=>{e.preventDefault();const b=form.querySelector('button[type=submit]');b.disabled=true;try{const d=await post('reset-password',{token:resetToken,...Object.fromEntries(new FormData(form))});say(d.message);resetToken='';form.remove()}catch(x){say(x.message);await challenge(form,'reset')}finally{b.disabled=false}}}
// Sequential initialization ensures the browser has its device cookie before the next challenge.
(async()=>{for(const [id,purpose] of [['loginForm','login'],['registerForm','register'],['forgotForm','forgot'],['emailResetForm','reset']]){const f=document.getElementById(id);if(f)await challenge(f,purpose)}})();
})();
